// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmiACogBEUlU3blBr10AZIaWbg__ZqMZQ',
    appId: '1:164426326641:web:598a293860cd05a02e31d0',
    messagingSenderId: '164426326641',
    projectId: 'messagingapplumina',
    authDomain: 'messagingapplumina.firebaseapp.com',
    storageBucket: 'messagingapplumina.firebasestorage.app',
    measurementId: 'G-HHEHPTCXQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtJN-HaoawJeYAW4doUruyMwcsM-wTTw',
    appId: '1:164426326641:android:4a4c6a93f6a4eb182e31d0',
    messagingSenderId: '164426326641',
    projectId: 'messagingapplumina',
    storageBucket: 'messagingapplumina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHauLTkxLIm94LzyxVxsyZq3daIIOPO9U',
    appId: '1:164426326641:ios:b3fd7858570f62e32e31d0',
    messagingSenderId: '164426326641',
    projectId: 'messagingapplumina',
    storageBucket: 'messagingapplumina.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHauLTkxLIm94LzyxVxsyZq3daIIOPO9U',
    appId: '1:164426326641:ios:b3fd7858570f62e32e31d0',
    messagingSenderId: '164426326641',
    projectId: 'messagingapplumina',
    storageBucket: 'messagingapplumina.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmiACogBEUlU3blBr10AZIaWbg__ZqMZQ',
    appId: '1:164426326641:web:3bff08de927514f82e31d0',
    messagingSenderId: '164426326641',
    projectId: 'messagingapplumina',
    authDomain: 'messagingapplumina.firebaseapp.com',
    storageBucket: 'messagingapplumina.firebasestorage.app',
    measurementId: 'G-6BNLW5J5R0',
  );
}
